# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Qiuran Homepage
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.


url: "https://lqrrrrr.github.io" # the base hostname & protocol for the site
baseurl: "" # the subpath of the site
og_image: /assets/img/profile-pic.jpg
#github_repo:"https://github.com/LQRrrrr/LQRrrrr.github.io.git"
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: ccccyyyylqr@gmail.com
      link: mailto:ccccyyyylqr@gmail.com
    - name: WeChat
      value: LQRweixin1101
      link: "#"
  follow:
    - name: Steam
      link: https://steamcommunity.com/profiles/76561198292446299/
      username: "@larisiji"
    - name: LinkedIn
      link: https://www.linkedin.com/in/秋燃-吕-492a90207/
    - name: GitHub
      link: http://github.com/LQRrrrr


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
